
device: cuda

data:
  dataset: bair64
  channels: 3
  logit_transform: False
  uniform_dequantization: False
  gaussian_dequantization: False
  rescaled: True
  num_frames: 7
  num_frames_cond: 9
  num_frames_future: 9

model:
  depth: deeper
  ngf: 192
  dropout: 0.1
  time_conditional: True
  version: DDPM
  output_all_frames: False
  num_forward_steps: 1000
  sigma_dist: cosine
  sigma_begin: 0.02
  sigma_end: 0.0001
  prob_mask_p: 0.5
  prob_mask_f: 0.5
  prob_mask_s: 1.0

optim:
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.000
  beta1: 0.9
  amsgrad: False
  eps: 0.00000001


train:
  num_epochs: 100
  batch_size: 64
  L1: False
  logging: True
  validation: True
  log_interval: 1000

eval:
  preds_per_test: 10
  subsample_steps: 100